- name: Download Go tarball
  become: true
  get_url:
    url: "{{ go_url }}"
    dest: "/tmp/{{ go_tarball }}"

- name: Remove any existing Go installation
  become: true
  file:
    path: "{{ go_install_dir }}"
    state: absent

- name: Extract Go to /usr/local
  become: true
  unarchive:
    src: "/tmp/{{ go_tarball }}"
    dest: /usr/local
    remote_src: yes
    mode: '0644'
