- name: Check if VSCode is installed
  command: which code
  register: code_exists
  failed_when: false
  changed_when: false

- block:
  - name: Add VS Code repository (deb822)
    become: true
    deb822_repository:
      name: vscode
      types: [deb]
      uris: https://packages.microsoft.com/repos/code
      suites: [stable]
      components: [main]
      architectures: [amd64]
      signed_by: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Install VS Code
    become: true
    apt:
      name: code
      state: present
      update_cache: yes

  - name: Ensure VS Code directories exist
    become: true
    become_user: "{{ student_user }}"
    file:
      path: "/home/{{ student_user }}/.vscode/extensions"
      state: directory
      mode: "0755"

  - name: Install VS Code extensions
    become: true
    become_user: "{{ student_user }}"
    shell: "/usr/bin/code --install-extension {{ item }}"
    loop:
      - rust-lang.rust-analyzer
      - golang.go
      - ms-azuretools.vscode-docker
      - dbaeumer.vscode-eslint
      - esbenp.prettier-vscode

  when: code_exists.rc != 0