---
- name: Minimal DCV Lab Setup
  hosts: localhost
  become: true

  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:

   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
