- name: Create password 
  include_tasks: password.yml

- name: Configure XFCE session
  include_tasks: xfce.yml

- name: NVM
  include_tasks: nvm.yml

- name: Golang environment
  include_tasks: golang-env.yml

- name: DCV Session
  include_tasks: dcv-session.yml