- name: Configure XFCE session
  become: true
  copy:
    dest: /home/student/.xsession
    content: |
      export $(dbus-launch)
      exec startxfce4
    owner: student
    group: student
    mode: '0644'