- hosts: lab
  gather_facts: true
  strategy: free
  roles:
    - role: ping
      tags: ping
    - role: tools
      tags: tools
    - role: dcv-session
      tags: dcv-session
    - role: repo
      tags: repo