- hosts: lab
  gather_facts: true
  strategy: free
  roles:
    - role: ping
      tags: ping
    - role: tools
      tags: tools
    - role: dcv-certificates
      tags: dcv-certificates
    - role: dcv-session
      tags: dcv-session, dcv-certificates
    - role: repo
      tags: repo
    - role: nginx-dcv-proxy
      tags: nginx-dcv-proxy